import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import ReduxProvider from "./_core/_providers/redux_provider";
import { readSidebarPref } from "./_core/_server/sidebar_pref";
import { Inter } from "next/font/google";
import { ModalProvider } from "./_core/_providers/modal_provider";


export const metadata: Metadata = {
  title: "Oinkstool",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter',
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const initialOpen = await readSidebarPref();

  return (
    <html className={inter.variable} suppressHydrationWarning >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function() {
              try {
                var ls = localStorage.getItem('theme');
                var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                var useDark = ls ? (ls === 'dark') : systemDark;
                var root = document.documentElement;
                root.classList.toggle('dark', useDark);
                root.style.colorScheme = useDark ? 'dark' : 'light';
              } catch (e) {}
            })();`,
          }}
        />
      </head>
      <body className="flex h-screen bg-[var(--bg-secondary)] overflow-hidden">  {/* h-screen + overflow-hidden */}
        <ReduxProvider initialSidebarOpen={initialOpen}>
          <ModalProvider>
            {children}
          </ModalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
