import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import ReduxProvider from "./_core/_providers/redux_provider";
import { readSidebarPref } from "./_core/_server/sidebar_pref";
import { Lexend } from "next/font/google";


export const metadata: Metadata = {
  title: "Oinkstool",
  description: "Generated by create next app",
};
const inter = Lexend({
  subsets:['latin'],
})

export default async function RootLayout({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) {

  const initialOpen = await readSidebarPref();

  return (
    <html suppressHydrationWarning >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function() {
              try {
                var ls = localStorage.getItem('theme'); // 사용자가 저장한 테마(light/dark)
                var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                var useDark = ls ? (ls === 'dark') : systemDark;
                var root = document.documentElement;
                root.classList.toggle('dark', useDark); // html.dark 붙여줌
                root.style.colorScheme = useDark ? 'dark' : 'light'; // 스크롤바/폼 UI도 맞춤
              } catch (e) {}
            })();
                      `,
          }}
        />
      </head>
      <body className="flex min-h-screen bg-[var(--bg-secondary)]">
        <ReduxProvider initialSidebarOpen={initialOpen}>
          <div className="flex-1 flex">
            <aside className="h-full">
              {sidebar}
            </aside>
            <main className="flex-1 flex">
              {children}
            </main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
